### ISSUE TITLE
Jupyter Notebook breaks while running Docker

### ISSUE THREAD

**Issue by DevAleks** [HadesArchitect/CaSpark#2]
On my PC with Ubuntu 18 Jupyter Notebook breaks down while running Docker. After running
```
docker-compose up -d
```
in logs I have an error:
```
jupyter_1  | Traceback (most recent call last):
jupyter_1  |   File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 535, in get
jupyter_1  |     value = obj._trait_values[self.name]
jupyter_1  | KeyError: 'runtime_dir'
jupyter_1  | 
jupyter_1  | During handling of the above exception, another exception occurred:
jupyter_1  | 
jupyter_1  | Traceback (most recent call last):
jupyter_1  |   File "/opt/conda/bin/jupyter-notebook", line 11, in <module>
jupyter_1  |     sys.exit(main())
jupyter_1  |   File "/opt/conda/lib/python3.8/site-packages/jupyter_core/application.py", line 270, in launch_instance
jupyter_1  |     return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
jupyter_1  |   File "/opt/conda/lib/python3.8/site-packages/traitlets/config/application.py", line 836, in launch_instance
jupyter_1  |     app.initialize(argv)
jupyter_1  |   File "/opt/conda/lib/python3.8/site-packages/traitlets/config/application.py", line 86, in inner
jupyter_1  |     return method(app, *args, **kwargs)
jupyter_1  |   File "/opt/conda/lib/python3.8/site-packages/notebook/notebookapp.py", line 2034, in initialize
jupyter_1  |     self.init_configurables()
jupyter_1  |   File "/opt/conda/lib/python3.8/site-packages/notebook/notebookapp.py", line 1563, in init_configurables
jupyter_1  |     connection_dir=self.runtime_dir,
jupyter_1  |   File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 575, in __get__
jupyter_1  |     return self.get(obj, cls)
jupyter_1  |   File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 538, in get
jupyter_1  |     default = obj.trait_defaults(self.name)
jupyter_1  |   File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 1577, in trait_defaults
jupyter_1  |     return self._get_trait_default_generator(names[0])(self)
jupyter_1  |   File "/opt/conda/lib/python3.8/site-packages/jupyter_core/application.py", line 100, in _runtime_dir_default
jupyter_1  |     ensure_dir_exists(rd, mode=0o700)
jupyter_1  |   File "/opt/conda/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
jupyter_1  |     os.makedirs(path, mode=mode)
jupyter_1  |   File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
jupyter_1  |     makedirs(head, exist_ok=exist_ok)
jupyter_1  |   File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
jupyter_1  |     makedirs(head, exist_ok=exist_ok)
jupyter_1  |   File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
jupyter_1  |     makedirs(head, exist_ok=exist_ok)
jupyter_1  |   File "/opt/conda/lib/python3.8/os.py", line 223, in makedirs
jupyter_1  |     mkdir(name, mode)
jupyter_1  | PermissionError: [Errno 13] Permission denied: '/home/jovyan/.local'
```

**Comment by HadesArchitect** [comment]
Hmmmm looks weird. It works well for me.
```
wks1 17:05:05 ~/caspark (master) $ dc logs -f jupyter
Attaching to caspark_jupyter_1
jupyter_1  | Executing the command: jupyter notebook --NotebookApp.password=sha1:a536879cf56d:a895a85b375e09f7d6a8211cdcd0e87f16aa4e60
jupyter_1  | [I 15:04:16.686 NotebookApp] JupyterLab extension loaded from /opt/conda/lib/python3.8/site-packages/jupyterlab
jupyter_1  | [I 15:04:16.687 NotebookApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
jupyter_1  | [I 15:04:16.690 NotebookApp] Serving notebooks from local directory: /home/jovyan
jupyter_1  | [I 15:04:16.690 NotebookApp] Jupyter Notebook 6.1.4 is running at:
jupyter_1  | [I 15:04:16.690 NotebookApp] http://993e25423c79:8888/
jupyter_1  | [I 15:04:16.691 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

**Comment by HadesArchitect** [comment]
Closed as not reproducible.
